--
-- Table structure for table `logos`
--

DROP TABLE IF EXISTS `logos`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `logos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `used` tinyint(1) DEFAULT 1,
  `enabled` tinyint(1) DEFAULT 1,
  `protected` tinyint(1) DEFAULT 0,
  `name` text DEFAULT NULL,
  `logo` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `logos`
--

LOCK TABLES `logos` WRITE;
/*!40000 ALTER TABLE `logos` DISABLE KEYS */;
INSERT INTO `logos` (name, logo, protected) VALUES ('admin', '/static/svg/icons/badges/badge-admin.svg', 1);
INSERT INTO `logos` (name, logo) VALUES ('4chan-2', '/static/svg/icons/badges/badge-4chan-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('4chan', '/static/svg/icons/badges/badge-4chan.svg');
INSERT INTO `logos` (name, logo) VALUES ('8ball', '/static/svg/icons/badges/badge-8ball.svg');
INSERT INTO `logos` (name, logo) VALUES ('alien-2', '/static/svg/icons/badges/badge-alien-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('alien-3', '/static/svg/icons/badges/badge-alien-3.svg');
INSERT INTO `logos` (name, logo) VALUES ('alien', '/static/svg/icons/badges/badge-alien.svg');
INSERT INTO `logos` (name, logo) VALUES ('anchor', '/static/svg/icons/badges/badge-anchor.svg');
INSERT INTO `logos` (name, logo) VALUES ('apple', '/static/svg/icons/badges/badge-apple.svg');
INSERT INTO `logos` (name, logo) VALUES ('atom', '/static/svg/icons/badges/badge-atom.svg');
INSERT INTO `logos` (name, logo) VALUES ('ax', '/static/svg/icons/badges/badge-ax.svg');
INSERT INTO `logos` (name, logo) VALUES ('b', '/static/svg/icons/badges/badge-b.svg');
INSERT INTO `logos` (name, logo) VALUES ('bar-graph', '/static/svg/icons/badges/badge-bar-graph.svg');
INSERT INTO `logos` (name, logo) VALUES ('barking', '/static/svg/icons/badges/badge-barking.svg');
INSERT INTO `logos` (name, logo) VALUES ('baseball', '/static/svg/icons/badges/badge-baseball.svg');
INSERT INTO `logos` (name, logo) VALUES ('basketball-hoop', '/static/svg/icons/badges/badge-basketball-hoop.svg');
INSERT INTO `logos` (name, logo) VALUES ('basketball', '/static/svg/icons/badges/badge-basketball.svg');
INSERT INTO `logos` (name, logo) VALUES ('bat', '/static/svg/icons/badges/badge-bat.svg');
INSERT INTO `logos` (name, logo) VALUES ('batman', '/static/svg/icons/badges/badge-batman.svg');
INSERT INTO `logos` (name, logo) VALUES ('battery', '/static/svg/icons/badges/badge-battery.svg');
INSERT INTO `logos` (name, logo) VALUES ('beaker', '/static/svg/icons/badges/badge-beaker.svg');
INSERT INTO `logos` (name, logo) VALUES ('bike', '/static/svg/icons/badges/badge-bike.svg');
INSERT INTO `logos` (name, logo) VALUES ('bluetooth', '/static/svg/icons/badges/badge-bluetooth.svg');
INSERT INTO `logos` (name, logo) VALUES ('boba-fett', '/static/svg/icons/badges/badge-boba-fett.svg');
INSERT INTO `logos` (name, logo) VALUES ('bomb', '/static/svg/icons/badges/badge-bomb.svg');
INSERT INTO `logos` (name, logo) VALUES ('bone', '/static/svg/icons/badges/badge-bone.svg');
INSERT INTO `logos` (name, logo) VALUES ('boomerang', '/static/svg/icons/badges/badge-boomerang.svg');
INSERT INTO `logos` (name, logo) VALUES ('bow-arrow', '/static/svg/icons/badges/badge-bow-arrow.svg');
INSERT INTO `logos` (name, logo) VALUES ('bowling-ball', '/static/svg/icons/badges/badge-bowling-ball.svg');
INSERT INTO `logos` (name, logo) VALUES ('bowling-pin', '/static/svg/icons/badges/badge-bowling-pin.svg');
INSERT INTO `logos` (name, logo) VALUES ('bowtie', '/static/svg/icons/badges/badge-bowtie.svg');
INSERT INTO `logos` (name, logo) VALUES ('box', '/static/svg/icons/badges/badge-box.svg');
INSERT INTO `logos` (name, logo) VALUES ('boxing-glove', '/static/svg/icons/badges/badge-boxing-glove.svg');
INSERT INTO `logos` (name, logo) VALUES ('broomstick', '/static/svg/icons/badges/badge-broomstick.svg');
INSERT INTO `logos` (name, logo) VALUES ('burger', '/static/svg/icons/badges/badge-burger.svg');
INSERT INTO `logos` (name, logo) VALUES ('c3po', '/static/svg/icons/badges/badge-c3po.svg');
INSERT INTO `logos` (name, logo) VALUES ('cactus', '/static/svg/icons/badges/badge-cactus.svg');
INSERT INTO `logos` (name, logo) VALUES ('california', '/static/svg/icons/badges/badge-california.svg');
INSERT INTO `logos` (name, logo) VALUES ('camera', '/static/svg/icons/badges/badge-camera.svg');
INSERT INTO `logos` (name, logo) VALUES ('captain-america', '/static/svg/icons/badges/badge-captain-america.svg');
INSERT INTO `logos` (name, logo) VALUES ('car', '/static/svg/icons/badges/badge-car.svg');
INSERT INTO `logos` (name, logo) VALUES ('cat', '/static/svg/icons/badges/badge-cat.svg');
INSERT INTO `logos` (name, logo) VALUES ('centaur', '/static/svg/icons/badges/badge-centaur.svg');
INSERT INTO `logos` (name, logo) VALUES ('checkmark', '/static/svg/icons/badges/badge-checkmark.svg');
INSERT INTO `logos` (name, logo) VALUES ('cherry', '/static/svg/icons/badges/badge-cherry.svg');
INSERT INTO `logos` (name, logo) VALUES ('chess-knight', '/static/svg/icons/badges/badge-chess-knight.svg');
INSERT INTO `logos` (name, logo) VALUES ('chess-rook', '/static/svg/icons/badges/badge-chess-rook.svg');
INSERT INTO `logos` (name, logo) VALUES ('chevron-corporal', '/static/svg/icons/badges/badge-chevron-corporal.svg');
INSERT INTO `logos` (name, logo) VALUES ('chevron-flag', '/static/svg/icons/badges/badge-chevron-flag.svg');
INSERT INTO `logos` (name, logo) VALUES ('cloud', '/static/svg/icons/badges/badge-cloud.svg');
INSERT INTO `logos` (name, logo) VALUES ('coffee', '/static/svg/icons/badges/badge-coffee.svg');
INSERT INTO `logos` (name, logo) VALUES ('command', '/static/svg/icons/badges/badge-command.svg');
INSERT INTO `logos` (name, logo) VALUES ('compass', '/static/svg/icons/badges/badge-compass.svg');
INSERT INTO `logos` (name, logo) VALUES ('computer-mouse', '/static/svg/icons/badges/badge-computer-mouse.svg');
INSERT INTO `logos` (name, logo) VALUES ('cone', '/static/svg/icons/badges/badge-cone.svg');
INSERT INTO `logos` (name, logo) VALUES ('corndog', '/static/svg/icons/badges/badge-corndog.svg');
INSERT INTO `logos` (name, logo) VALUES ('crown', '/static/svg/icons/badges/badge-crown.svg');
INSERT INTO `logos` (name, logo) VALUES ('cupcake', '/static/svg/icons/badges/badge-cupcake.svg');
INSERT INTO `logos` (name, logo) VALUES ('cursor', '/static/svg/icons/badges/badge-cursor.svg');
INSERT INTO `logos` (name, logo) VALUES ('darth-vader', '/static/svg/icons/badges/badge-darth-vader.svg');
INSERT INTO `logos` (name, logo) VALUES ('deadpool', '/static/svg/icons/badges/badge-deadpool.svg');
INSERT INTO `logos` (name, logo) VALUES ('deal-with-it', '/static/svg/icons/badges/badge-deal-with-it.svg');
INSERT INTO `logos` (name, logo) VALUES ('deathly-hollows', '/static/svg/icons/badges/badge-deathly-hollows.svg');
INSERT INTO `logos` (name, logo) VALUES ('diamond', '/static/svg/icons/badges/badge-diamond.svg');
INSERT INTO `logos` (name, logo) VALUES ('dirtbike', '/static/svg/icons/badges/badge-dirtbike.svg');
INSERT INTO `logos` (name, logo) VALUES ('dog', '/static/svg/icons/badges/badge-dog.svg');
INSERT INTO `logos` (name, logo) VALUES ('double-ax', '/static/svg/icons/badges/badge-double-ax.svg');
INSERT INTO `logos` (name, logo) VALUES ('drop', '/static/svg/icons/badges/badge-drop.svg');
INSERT INTO `logos` (name, logo) VALUES ('dumbell', '/static/svg/icons/badges/badge-dumbell.svg');
INSERT INTO `logos` (name, logo) VALUES ('egg', '/static/svg/icons/badges/badge-egg.svg');
INSERT INTO `logos` (name, logo) VALUES ('elephant', '/static/svg/icons/badges/badge-elephant.svg');
INSERT INTO `logos` (name, logo) VALUES ('eye', '/static/svg/icons/badges/badge-eye.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-cloud', '/static/svg/icons/badges/badge-face-cloud.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-helmeted', '/static/svg/icons/badges/badge-face-helmeted.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-sad', '/static/svg/icons/badges/badge-face-sad.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-star', '/static/svg/icons/badges/badge-face-star.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-toast', '/static/svg/icons/badges/badge-face-toast.svg');
INSERT INTO `logos` (name, logo) VALUES ('face-tongue', '/static/svg/icons/badges/badge-face-tongue.svg');
INSERT INTO `logos` (name, logo) VALUES ('feather', '/static/svg/icons/badges/badge-feather.svg');
INSERT INTO `logos` (name, logo) VALUES ('flag', '/static/svg/icons/badges/badge-flag.svg');
INSERT INTO `logos` (name, logo) VALUES ('flower-2', '/static/svg/icons/badges/badge-flower-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('flower', '/static/svg/icons/badges/badge-flower.svg');
INSERT INTO `logos` (name, logo) VALUES ('football', '/static/svg/icons/badges/badge-football.svg');
INSERT INTO `logos` (name, logo) VALUES ('fork', '/static/svg/icons/badges/badge-fork.svg');
INSERT INTO `logos` (name, logo) VALUES ('fries', '/static/svg/icons/badges/badge-fries.svg');
INSERT INTO `logos` (name, logo) VALUES ('game-controller', '/static/svg/icons/badges/badge-game-controller.svg');
INSERT INTO `logos` (name, logo) VALUES ('glasses', '/static/svg/icons/badges/badge-glasses.svg');
INSERT INTO `logos` (name, logo) VALUES ('green-lantern', '/static/svg/icons/badges/badge-green-lantern.svg');
INSERT INTO `logos` (name, logo) VALUES ('guy-fawkes', '/static/svg/icons/badges/badge-guy-fawkes.svg');
INSERT INTO `logos` (name, logo) VALUES ('hat-viking', '/static/svg/icons/badges/badge-hat-viking.svg');
INSERT INTO `logos` (name, logo) VALUES ('hat-witch', '/static/svg/icons/badges/badge-hat-witch.svg');
INSERT INTO `logos` (name, logo) VALUES ('head-lego', '/static/svg/icons/badges/badge-head-lego.svg');
INSERT INTO `logos` (name, logo) VALUES ('headphones', '/static/svg/icons/badges/badge-headphones.svg');
INSERT INTO `logos` (name, logo) VALUES ('heart', '/static/svg/icons/badges/badge-heart.svg');
INSERT INTO `logos` (name, logo) VALUES ('high-heel', '/static/svg/icons/badges/badge-high-heel.svg');
INSERT INTO `logos` (name, logo) VALUES ('home', '/static/svg/icons/badges/badge-home.svg');
INSERT INTO `logos` (name, logo) VALUES ('hook', '/static/svg/icons/badges/badge-hook.svg');
INSERT INTO `logos` (name, logo) VALUES ('hotdog', '/static/svg/icons/badges/badge-hotdog.svg');
INSERT INTO `logos` (name, logo) VALUES ('html-file-2', '/static/svg/icons/badges/badge-html-file-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('html-file', '/static/svg/icons/badges/badge-html-file.svg');
INSERT INTO `logos` (name, logo) VALUES ('html', '/static/svg/icons/badges/badge-html.svg');
INSERT INTO `logos` (name, logo) VALUES ('ice-cream', '/static/svg/icons/badges/badge-ice-cream.svg');
INSERT INTO `logos` (name, logo) VALUES ('infinity', '/static/svg/icons/badges/badge-infinity.svg');
INSERT INTO `logos` (name, logo) VALUES ('invader-2', '/static/svg/icons/badges/badge-invader-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('invader', '/static/svg/icons/badges/badge-invader.svg');
INSERT INTO `logos` (name, logo) VALUES ('iron-man', '/static/svg/icons/badges/badge-iron-man.svg');
INSERT INTO `logos` (name, logo) VALUES ('jack-o-lantern', '/static/svg/icons/badges/badge-jack-o-lantern.svg');
INSERT INTO `logos` (name, logo) VALUES ('jeep', '/static/svg/icons/badges/badge-jeep.svg');
INSERT INTO `logos` (name, logo) VALUES ('kangaroo', '/static/svg/icons/badges/badge-kangaroo.svg');
INSERT INTO `logos` (name, logo) VALUES ('kanye-glasses', '/static/svg/icons/badges/badge-kanye-glasses.svg');
INSERT INTO `logos` (name, logo) VALUES ('key', '/static/svg/icons/badges/badge-key.svg');
INSERT INTO `logos` (name, logo) VALUES ('kite', '/static/svg/icons/badges/badge-kite.svg');
INSERT INTO `logos` (name, logo) VALUES ('knife', '/static/svg/icons/badges/badge-knife.svg');
INSERT INTO `logos` (name, logo) VALUES ('lightbulb', '/static/svg/icons/badges/badge-lightbulb.svg');
INSERT INTO `logos` (name, logo) VALUES ('lightning', '/static/svg/icons/badges/badge-lightning.svg');
INSERT INTO `logos` (name, logo) VALUES ('location', '/static/svg/icons/badges/badge-location.svg');
INSERT INTO `logos` (name, logo) VALUES ('man-newspaper', '/static/svg/icons/badges/badge-man-newspaper.svg');
INSERT INTO `logos` (name, logo) VALUES ('marker', '/static/svg/icons/badges/badge-marker.svg');
INSERT INTO `logos` (name, logo) VALUES ('monkey', '/static/svg/icons/badges/badge-monkey.svg');
INSERT INTO `logos` (name, logo) VALUES ('monopoly-man', '/static/svg/icons/badges/badge-monopoly-man.svg');
INSERT INTO `logos` (name, logo) VALUES ('moon', '/static/svg/icons/badges/badge-moon.svg');
INSERT INTO `logos` (name, logo) VALUES ('moustache', '/static/svg/icons/badges/badge-moustache.svg');
INSERT INTO `logos` (name, logo) VALUES ('music', '/static/svg/icons/badges/badge-music.svg');
INSERT INTO `logos` (name, logo) VALUES ('mystery-man', '/static/svg/icons/badges/badge-mystery-man.svg');
INSERT INTO `logos` (name, logo) VALUES ('nascar', '/static/svg/icons/badges/badge-nascar.svg');
INSERT INTO `logos` (name, logo) VALUES ('pacman-ghost', '/static/svg/icons/badges/badge-pacman-ghost.svg');
INSERT INTO `logos` (name, logo) VALUES ('pacman', '/static/svg/icons/badges/badge-pacman.svg');
INSERT INTO `logos` (name, logo) VALUES ('paperclip', '/static/svg/icons/badges/badge-paperclip.svg');
INSERT INTO `logos` (name, logo) VALUES ('peace-sign', '/static/svg/icons/badges/badge-peace-sign.svg');
INSERT INTO `logos` (name, logo) VALUES ('peace', '/static/svg/icons/badges/badge-peace.svg');
INSERT INTO `logos` (name, logo) VALUES ('pencil-sharpener', '/static/svg/icons/badges/badge-pencil-sharpener.svg');
INSERT INTO `logos` (name, logo) VALUES ('penguin', '/static/svg/icons/badges/badge-penguin.svg');
INSERT INTO `logos` (name, logo) VALUES ('penrose-triangle', '/static/svg/icons/badges/badge-penrose-triangle.svg');
INSERT INTO `logos` (name, logo) VALUES ('pi', '/static/svg/icons/badges/badge-pi.svg');
INSERT INTO `logos` (name, logo) VALUES ('picasa', '/static/svg/icons/badges/badge-picasa.svg');
INSERT INTO `logos` (name, logo) VALUES ('plane', '/static/svg/icons/badges/badge-plane.svg');
INSERT INTO `logos` (name, logo) VALUES ('plasma-gun', '/static/svg/icons/badges/badge-plasma-gun.svg');
INSERT INTO `logos` (name, logo) VALUES ('plug', '/static/svg/icons/badges/badge-plug.svg');
INSERT INTO `logos` (name, logo) VALUES ('pokemon', '/static/svg/icons/badges/badge-pokemon.svg');
INSERT INTO `logos` (name, logo) VALUES ('puma', '/static/svg/icons/badges/badge-puma.svg');
INSERT INTO `logos` (name, logo) VALUES ('pyramid', '/static/svg/icons/badges/badge-pyramid.svg');
INSERT INTO `logos` (name, logo) VALUES ('r2d2', '/static/svg/icons/badges/badge-r2d2.svg');
INSERT INTO `logos` (name, logo) VALUES ('radiation', '/static/svg/icons/badges/badge-radiation.svg');
INSERT INTO `logos` (name, logo) VALUES ('rainbow', '/static/svg/icons/badges/badge-rainbow.svg');
INSERT INTO `logos` (name, logo) VALUES ('reset', '/static/svg/icons/badges/badge-reset.svg');
INSERT INTO `logos` (name, logo) VALUES ('revolver', '/static/svg/icons/badges/badge-revolver.svg');
INSERT INTO `logos` (name, logo) VALUES ('robber', '/static/svg/icons/badges/badge-robber.svg');
INSERT INTO `logos` (name, logo) VALUES ('robot', '/static/svg/icons/badges/badge-robot.svg');
INSERT INTO `logos` (name, logo) VALUES ('rocker', '/static/svg/icons/badges/badge-rocker.svg');
INSERT INTO `logos` (name, logo) VALUES ('rocket', '/static/svg/icons/badges/badge-rocket.svg');
INSERT INTO `logos` (name, logo) VALUES ('rollerblade', '/static/svg/icons/badges/badge-rollerblade.svg');
INSERT INTO `logos` (name, logo) VALUES ('sailboat', '/static/svg/icons/badges/badge-sailboat.svg');
INSERT INTO `logos` (name, logo) VALUES ('saturn', '/static/svg/icons/badges/badge-saturn.svg');
INSERT INTO `logos` (name, logo) VALUES ('sauron', '/static/svg/icons/badges/badge-sauron.svg');
INSERT INTO `logos` (name, logo) VALUES ('sharethis', '/static/svg/icons/badges/badge-sharethis.svg');
INSERT INTO `logos` (name, logo) VALUES ('shark', '/static/svg/icons/badges/badge-shark.svg');
INSERT INTO `logos` (name, logo) VALUES ('shirt', '/static/svg/icons/badges/badge-shirt.svg');
INSERT INTO `logos` (name, logo) VALUES ('shoe', '/static/svg/icons/badges/badge-shoe.svg');
INSERT INTO `logos` (name, logo) VALUES ('skateboard', '/static/svg/icons/badges/badge-skateboard.svg');
INSERT INTO `logos` (name, logo) VALUES ('skateboarder', '/static/svg/icons/badges/badge-skateboarder.svg');
INSERT INTO `logos` (name, logo) VALUES ('skiier', '/static/svg/icons/badges/badge-skiier.svg');
INSERT INTO `logos` (name, logo) VALUES ('skull-crossbones', '/static/svg/icons/badges/badge-skull-crossbones.svg');
INSERT INTO `logos` (name, logo) VALUES ('snowboarder', '/static/svg/icons/badges/badge-snowboarder.svg');
INSERT INTO `logos` (name, logo) VALUES ('soccerball', '/static/svg/icons/badges/badge-soccerball.svg');
INSERT INTO `logos` (name, logo) VALUES ('sock', '/static/svg/icons/badges/badge-sock.svg');
INSERT INTO `logos` (name, logo) VALUES ('spaceship-2', '/static/svg/icons/badges/badge-spaceship-2.svg');
INSERT INTO `logos` (name, logo) VALUES ('spaceship', '/static/svg/icons/badges/badge-spaceship.svg');
INSERT INTO `logos` (name, logo) VALUES ('speech-bubble', '/static/svg/icons/badges/badge-speech-bubble.svg');
INSERT INTO `logos` (name, logo) VALUES ('speeding-ball', '/static/svg/icons/badges/badge-speeding-ball.svg');
INSERT INTO `logos` (name, logo) VALUES ('spiderweb', '/static/svg/icons/badges/badge-spiderweb.svg');
INSERT INTO `logos` (name, logo) VALUES ('stars', '/static/svg/icons/badges/badge-stars.svg');
INSERT INTO `logos` (name, logo) VALUES ('stereo', '/static/svg/icons/badges/badge-stereo.svg');
INSERT INTO `logos` (name, logo) VALUES ('stormtrooper', '/static/svg/icons/badges/badge-stormtrooper.svg');
INSERT INTO `logos` (name, logo) VALUES ('swimmer', '/static/svg/icons/badges/badge-swimmer.svg');
INSERT INTO `logos` (name, logo) VALUES ('swords', '/static/svg/icons/badges/badge-swords.svg');
INSERT INTO `logos` (name, logo) VALUES ('tank', '/static/svg/icons/badges/badge-tank.svg');
INSERT INTO `logos` (name, logo) VALUES ('tennis', '/static/svg/icons/badges/badge-tennis.svg');
INSERT INTO `logos` (name, logo) VALUES ('tetris-j', '/static/svg/icons/badges/badge-tetris-j.svg');
INSERT INTO `logos` (name, logo) VALUES ('tetris-t', '/static/svg/icons/badges/badge-tetris-t.svg');
INSERT INTO `logos` (name, logo) VALUES ('tetris-z', '/static/svg/icons/badges/badge-tetris-z.svg');
INSERT INTO `logos` (name, logo) VALUES ('thors-hammer', '/static/svg/icons/badges/badge-thors-hammer.svg');
INSERT INTO `logos` (name, logo) VALUES ('throwing-star', '/static/svg/icons/badges/badge-throwing-star.svg');
INSERT INTO `logos` (name, logo) VALUES ('thumbsup', '/static/svg/icons/badges/badge-thumbsup.svg');
INSERT INTO `logos` (name, logo) VALUES ('tooth', '/static/svg/icons/badges/badge-tooth.svg');
INSERT INTO `logos` (name, logo) VALUES ('tophat', '/static/svg/icons/badges/badge-tophat.svg');
INSERT INTO `logos` (name, logo) VALUES ('traffic-cone', '/static/svg/icons/badges/badge-traffic-cone.svg');
INSERT INTO `logos` (name, logo) VALUES ('trophy', '/static/svg/icons/badges/badge-trophy.svg');
INSERT INTO `logos` (name, logo) VALUES ('turkey-leg', '/static/svg/icons/badges/badge-turkey-leg.svg');
INSERT INTO `logos` (name, logo) VALUES ('umbrella', '/static/svg/icons/badges/badge-umbrella.svg');
INSERT INTO `logos` (name, logo) VALUES ('unicorn', '/static/svg/icons/badges/badge-unicorn.svg');
INSERT INTO `logos` (name, logo) VALUES ('unicycle', '/static/svg/icons/badges/badge-unicycle.svg');
INSERT INTO `logos` (name, logo) VALUES ('vampire', '/static/svg/icons/badges/badge-vampire.svg');
INSERT INTO `logos` (name, logo) VALUES ('venn-diagram', '/static/svg/icons/badges/badge-venn-diagram.svg');
INSERT INTO `logos` (name, logo) VALUES ('volleyball', '/static/svg/icons/badges/badge-volleyball.svg');
INSERT INTO `logos` (name, logo) VALUES ('vulcan-salute', '/static/svg/icons/badges/badge-vulcan-salute.svg');
INSERT INTO `logos` (name, logo) VALUES ('watch', '/static/svg/icons/badges/badge-watch.svg');
INSERT INTO `logos` (name, logo) VALUES ('watergun', '/static/svg/icons/badges/badge-watergun.svg');
INSERT INTO `logos` (name, logo) VALUES ('whale', '/static/svg/icons/badges/badge-whale.svg');
INSERT INTO `logos` (name, logo) VALUES ('whistle', '/static/svg/icons/badges/badge-whistle.svg');
INSERT INTO `logos` (name, logo) VALUES ('wifi', '/static/svg/icons/badges/badge-wifi.svg');
INSERT INTO `logos` (name, logo) VALUES ('x-and-o', '/static/svg/icons/badges/badge-x-and-o.svg');
INSERT INTO `logos` (name, logo) VALUES ('x-men', '/static/svg/icons/badges/badge-x-men.svg');
/*!40000 ALTER TABLE `logos` ENABLE KEYS */;
UNLOCK TABLES;
